// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://luqvqwpglceeqtbbtvuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1cXZxd3BnbGNlZXF0YmJ0dnVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzOTIyNTIsImV4cCI6MjA2MDk2ODI1Mn0.1mbyRIBDJI9DBBeHlgtS4MnDFGUiOXBM0-Dy_1whvvI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});