name: Ikabay Netlify Agent (Free, Auto-resume)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"   # reprise automatique toutes les 10 min

permissions:
  contents: write

jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: |
          npm init -y >/dev/null 2>&1 || true
          npm i axios cheerio netlify-cli @octokit/rest --silent

      - name: Run agent (ingest + enhance + deploy)
        env:
          SOURCE_URL: "https://gregarious-stroopwafel-a5e730.netlify.app/"
          STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: node scripts/ingest-from-netlify.js
